### ISSUE TITLE
Cannot download TrustCoreAndroid:0.01.6 from jitpack.io

### ISSUE THREAD

**Issue by madhat1** [TrustWallet/Web3View#7]
Hi,

I'm getting the failure below, please help!
Is this a jitpack issue or have you closed the access to the resources?

FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.TrustWallet:TrustCoreAndroid:0.01.6.
  Required by:
      project :app
   > Could not resolve com.github.TrustWallet:TrustCoreAndroid:0.01.6.
      > Could not get resource 'https://jitpack.io/com/github/TrustWallet/TrustCoreAndroid/0.01.6/TrustCoreAndroid-0.01.6.pom'.
         > Could not GET 'https://jitpack.io/com/github/TrustWallet/TrustCoreAndroid/0.01.6/TrustCoreAndroid-0.01.6.pom'. Received status code 401 from server: Unauthorized

**Comment by v991314** [comment]
最新版突然就不能用了0.01.6  https://jitpack.io/#TrustWallet/Web3View
